#!/usr/bin/env node
// VibeCatch Remote Worker — dependency-free Node ESM HTTP server
// Node >=18, zero npm dependencies (builtins only).
// Importing MUST NOT start the server; server starts only when executed directly.

import http from 'node:http';
import { URL } from 'node:url';
import { spawn } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';

// ---------------------------------------------------------------------------
// corsHeaders — CORS + Private Network headers for browser PWA access
// ---------------------------------------------------------------------------

export function corsHeaders() {
  return {
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Methods': 'GET,OPTIONS',
    'Access-Control-Allow-Headers': '*',
    'Access-Control-Allow-Private-Network': 'true',
    'Content-Type': 'application/json',
  };
}

const CORS_ONLY = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Methods': 'GET,OPTIONS',
  'Access-Control-Allow-Headers': '*',
  'Access-Control-Allow-Private-Network': 'true',
};

// ---------------------------------------------------------------------------
// parseRangeHeader — parse Range header or query value
// ---------------------------------------------------------------------------

export function parseRangeHeader(h) {
  if (typeof h !== 'string') return null;
  const m = /^bytes=(\d+)-(\d*)$/.exec(h);
  if (!m) return null;
  const start = Number(m[1]);
  const end = m[2] === '' ? undefined : Number(m[2]);
  return { start, end };
}

// ---------------------------------------------------------------------------
// sanitizeFilename — strip illegal chars for Content-Disposition
// ---------------------------------------------------------------------------

export function sanitizeFilename(name) {
  return String(name || '').replace(/[^A-Za-z0-9 ._-]/g, '_').substring(0, 200);
}

// ---------------------------------------------------------------------------
// validVideoId — YouTube video IDs are 11 chars [A-Za-z0-9_-] but we
// accept anything that looks like one (not a plain all-caps word).
// ---------------------------------------------------------------------------

const YT_ID_RE = /^[A-Za-z0-9_-]{4,}$/;

export function validVideoId(id) {
  if (!id || typeof id !== 'string') return false;
  if (!YT_ID_RE.test(id)) return false;
  // Reject all-uppercase words — real YouTube IDs always contain
  // at least one lowercase letter or digit mixed in.
  if (/^[A-Z]+$/.test(id)) return false;
  return true;
}

// ---------------------------------------------------------------------------
// startServer — HTTP server on configurable port
// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// resolveCookiesPath — find Netscape cookies.txt (opts > env > stateDir)
// ---------------------------------------------------------------------------

export function resolveCookiesPath(opts = {}) {
  if (opts.cookiesPath) {
    try { fs.accessSync(opts.cookiesPath); return opts.cookiesPath; } catch { return null; }
  }
  if (process.env.VIBECATCH_YT_COOKIES) {
    try { fs.accessSync(process.env.VIBECATCH_YT_COOKIES); return process.env.VIBECATCH_YT_COOKIES; } catch {}
  }
  const baseDir = opts.stateDir || path.join(os.tmpdir(), 'vibecatch-worker');
  const statePath = path.join(baseDir, 'cookies.txt');
  try { fs.accessSync(statePath); return statePath; } catch {}
  return null;
}

// ---------------------------------------------------------------------------
// ensureBootstrapCookies — auto-create a minimal Netscape stub so yt-dlp can
// bypass the YouTube bot-wall out of the box (ANY cookiejar defeats it).
// Critical on datacenter IPs (HF Spaces): without a jar every request 502s.
// ---------------------------------------------------------------------------

export function ensureBootstrapCookies(opts = {}, stateDir) {
  if (opts.cookiesPath) return null;
  if (process.env.VIBECATCH_YT_COOKIES) return null;
  try {
    fs.mkdirSync(stateDir, { recursive: true });
    const p = path.join(stateDir, 'cookies.txt');
    if (!fs.existsSync(p)) {
      const stub = [
        '# Netscape HTTP Cookie File',
        '# Auto-generated by vibecatch remote worker (bootstrap stub).',
        '.youtube.com\tTRUE\t/\tTRUE\t9999999999\tVISITOR_INFO1_LIVE\tvibecatch-bootstrap',
        '.youtube.com\tTRUE\t/\tTRUE\t9999999999\tYSC\tvibecatch-bootstrap',
        '',
      ].join('\n');
      fs.writeFileSync(p, stub);
    }
    return p;
  } catch { return null; }
}

function ytDlpArgs(cookiesPath, extra) {
  const args = ['-f', 'bestaudio[ext=m4a]/bestaudio', '--no-playlist', '--js-runtimes', 'node'];
  const potRaw = process.env.VIBECATCH_POT_URL !== undefined ? process.env.VIBECATCH_POT_URL : 'http://127.0.0.1:4416';
  const potUrl = typeof potRaw === 'string' ? potRaw.trim() : '';
  if (potUrl) {
    args.push('--extractor-args', 'youtube:player_client=mweb,tv_simply');
    args.push('--extractor-args', 'youtubepot-bgutilhttp:base_url=' + potUrl);
  }
  if (cookiesPath) args.push('--cookies', cookiesPath);
  args.push(...extra);
  return args;
}

export function startServer(port = 8795, opts = {}) {
  const ytdlpPath = opts.ytdlpPath || 'yt-dlp';
  const stateDir = opts.stateDir || path.join(os.tmpdir(), 'vibecatch-worker');
  const spawnOpts = process.platform === 'win32' && /\.(cmd|bat)$/i.test(ytdlpPath) ? { shell: true } : {};

  ensureBootstrapCookies(opts, stateDir);
  const cookiesAtBoot = resolveCookiesPath({ ...opts, stateDir });

  const cacheDir = path.join(stateDir, 'cache');
  try { fs.mkdirSync(cacheDir, { recursive: true }); } catch {}

  function cacheFinalPath(videoId) {
    return path.join(cacheDir, videoId + '.m4a');
  }

  const inflight = new Map();

  function ensureCached(videoId) {
    const finalP = cacheFinalPath(videoId);
    try { fs.accessSync(finalP); return Promise.resolve(finalP); } catch {}
    if (inflight.has(videoId)) return inflight.get(videoId);
    const p = new Promise((resolve) => {
      let child;
      try {
      child = spawn(ytdlpPath, ytDlpArgs(cookiesAtBoot, ['-o', '-', 'https://www.youtube.com/watch?v=' + videoId]), spawnOpts);
    } catch { resolve(null); return; }
      const partP = finalP + '.part';
      const ws = fs.createWriteStream(partP);
      let wrote = false;
      child.stdout.on('data', (c) => { wrote = true; try { ws.write(c); } catch {} });
      child.on('close', (code) => {
        ws.end(() => {
          let out = null;
          if (code === 0 && wrote) {
            try { fs.renameSync(partP, finalP); out = finalP; } catch {}
          } else {
            try { fs.unlinkSync(partP); } catch {}
          }
          inflight.delete(videoId);
          resolve(out);
        });
      });
      child.on('error', () => {
        try { ws.end(); } catch {}
        try { fs.unlinkSync(partP); } catch {}
        inflight.delete(videoId);
        resolve(null);
      });
    });
    inflight.set(videoId, p);
    return p;
  }

  const server = http.createServer(async (req, res) => {
    const urlObj = new URL(req.url || '/', `http://127.0.0.1:${port}`);
    const pathname = urlObj.pathname;

    // CORS preflight
    if (req.method === 'OPTIONS') {
      res.writeHead(204, CORS_ONLY);
      res.end();
      return;
    }

    // GET /vibecheck
    if (req.method === 'GET' && pathname === '/vibecheck') {
      res.writeHead(200, corsHeaders());
      res.end(JSON.stringify({ ok: true, name: 'vibecatch-remote-worker', version: '1.0.0' }));
      return;
    }

    // GET /resolve?videoId=<id>
    if (req.method === 'GET' && pathname === '/resolve') {
      const videoId = urlObj.searchParams.get('videoId');
      if (!videoId || !validVideoId(videoId)) {
        res.writeHead(502, corsHeaders());
        res.end(JSON.stringify({ error: 'invalid videoId' }));
        return;
      }

      const args = ytDlpArgs(cookiesAtBoot, ['--dump-json', 'https://www.youtube.com/watch?v=' + videoId]);

      const result = await new Promise((resolve) => {
        let child;
        try {
          child = spawn(ytdlpPath, args, spawnOpts);
        } catch (e) {
          resolve({ exitCode: -1, stdout: '', stderr: e.message });
          return;
        }
        let stdout = '';
        let stderr = '';
        child.stdout.on('data', (c) => { stdout += c.toString(); });
        child.stderr.on('data', (c) => { stderr += c.toString(); });
        child.on('close', (code) => { resolve({ exitCode: code, stdout, stderr }); });
        child.on('error', (e) => { resolve({ exitCode: -1, stdout: '', stderr: e.message }); });
      });

      if (result.exitCode !== 0 || !result.stdout.trim()) {
        const stderrTail = result.stderr.slice(-200).trim();
        res.writeHead(502, corsHeaders());
        res.end(JSON.stringify({ error: stderrTail || 'yt-dlp failed with code ' + result.exitCode }));
        return;
      }

      try {
        const json = JSON.parse(result.stdout.trim());
        res.writeHead(200, corsHeaders());
        res.end(JSON.stringify({
          videoId: videoId,
          title: json.title || '',
          artist: json.artist || json.uploader || json.author || '',
          duration: Math.round(json.duration || 0),
          thumbnail: json.thumbnail || '',
          uploader: json.uploader || json.author || '',
          audioUrl: json.url || '',
        }));
      } catch {
        res.writeHead(502, corsHeaders());
        res.end(JSON.stringify({ error: 'invalid yt-dlp output' }));
      }
      return;
    }

    // GET /download?videoId=<id>[&title=&artist=&range=]
    if (req.method === 'GET' && pathname === '/download') {
      const videoId = urlObj.searchParams.get('videoId');
      if (!videoId || !validVideoId(videoId)) {
        res.writeHead(502, corsHeaders());
        res.end(JSON.stringify({ error: 'invalid videoId' }));
        return;
      }

      const title = sanitizeFilename(urlObj.searchParams.get('title') || 'YouTube Audio');
      const filename = title + '.m4a';

      // Warm path — serve straight from the full-file cache
      const finalP = cacheFinalPath(videoId);
      let cached = false;
      try { fs.accessSync(finalP); cached = true; } catch {}
      if (cached) {
        serveCachedFile(res, req, finalP, filename, urlObj);
        return;
      }

      // In-flight fill? wait for it, then serve
      if (inflight.has(videoId)) {
        const out = await inflight.get(videoId);
        if (out) {
          serveCachedFile(res, req, finalP, filename, urlObj);
          return;
        }
        res.writeHead(502, corsHeaders());
        res.end(JSON.stringify({ error: 'yt-dlp failed to fetch this video' }));
        return;
      }

      // Cold download — stream and cache
      const args = ytDlpArgs(cookiesAtBoot, ['-o', '-', 'https://www.youtube.com/watch?v=' + videoId]);

      let child;
      try {
        child = spawn(ytdlpPath, args, spawnOpts);
      } catch (e) {
        res.writeHead(502, corsHeaders());
        res.end(JSON.stringify({ error: 'failed to spawn yt-dlp: ' + e.message }));
        return;
      }

      const partP = finalP + '.part';
      const ws = fs.createWriteStream(partP);
      let resolveDone;
      const done = new Promise((r) => { resolveDone = r; });
      inflight.set(videoId, done);

      const audioHeaders = {
        'Content-Type': 'audio/mp4',
        'Content-Disposition': 'attachment; filename="' + filename + '"',
        'Access-Control-Allow-Origin': '*',
        'Access-Control-Allow-Private-Network': 'true',
        'Access-Control-Allow-Methods': 'GET,OPTIONS',
        'Access-Control-Allow-Headers': '*',
      };

      const stderrChunks = [];
      if (child.stderr) child.stderr.on('data', (d) => { stderrChunks.push(d); });
      let headersSent = false;
      let bytesSent = false;

      // Proxy/tunnel TTFB deadline (mirror of the local node): see test/ttfb-headers
      const HEADER_DEADLINE_MS = 2000;
      const headerDeadline = setTimeout(() => {
        if (!headersSent && !res.headersSent && !res.writableEnded && !res.destroyed) {
          headersSent = true;
          res.writeHead(200, audioHeaders);
          res.flushHeaders();
        }
      }, HEADER_DEADLINE_MS);

      child.stdout.on('data', (chunk) => {
        if (!headersSent) { headersSent = true; clearTimeout(headerDeadline); res.writeHead(200, audioHeaders); }
        bytesSent = true;
        res.write(chunk);
        try { ws.write(chunk); } catch {}
      });

      child.on('close', (code) => {
        clearTimeout(headerDeadline);
        ws.end(() => {
          let out = null;
          if (code === 0 && bytesSent) {
            try { fs.renameSync(partP, finalP); out = finalP; } catch {}
          } else {
            try { fs.unlinkSync(partP); } catch {}
          }
          inflight.delete(videoId);
          if (resolveDone) resolveDone(out);
        });
        if (!bytesSent) {
          if (res.writableEnded || res.destroyed) return;
          if (res.headersSent) { try { res.end(); } catch {} return; }
          const stderrTail = Buffer.concat(stderrChunks).toString('utf8').slice(-200).trim();
          res.writeHead(502, corsHeaders());
          res.end(JSON.stringify({ error: 'yt-dlp exited with code ' + code + (stderrTail ? ': ' + stderrTail : '') }));
        } else {
          res.end();
        }
      });

      child.on('error', (e) => {
        clearTimeout(headerDeadline);
        try { ws.end(); } catch {}
        try { fs.unlinkSync(partP); } catch {}
        inflight.delete(videoId);
        if (resolveDone) resolveDone(null);
        if (!bytesSent) {
          if (!res.headersSent) {
            res.writeHead(502, corsHeaders());
          }
          res.end(JSON.stringify({ error: 'yt-dlp process error: ' + e.message }));
        } else {
          try { res.end(); } catch {}
        }
      });

      req.on('close', () => { if (child && !child.killed) child.kill(); });
      return;
    }

    // 404
    res.writeHead(404, corsHeaders());
    res.end(JSON.stringify({ error: 'not found' }));
  });

  function serveCachedFile(res, req, filePath, filename, urlObj) {
    let size = 0;
    try { size = fs.statSync(filePath).size; } catch {
      res.writeHead(502, corsHeaders());
      res.end(JSON.stringify({ error: 'cached file vanished' }));
      return;
    }

    const base = {
      'Content-Type': 'audio/mp4',
      'Content-Disposition': 'attachment; filename="' + filename + '"',
      'Access-Control-Allow-Origin': '*',
      'Access-Control-Allow-Private-Network': 'true',
      'Access-Control-Allow-Methods': 'GET,OPTIONS',
      'Access-Control-Allow-Headers': '*',
      'Accept-Ranges': 'bytes',
    };

    // Parse range from query param OR Range header
    let range = parseRangeHeader(urlObj.searchParams.get('range'));
    if (!range) range = parseRangeHeader(req.headers && req.headers.range);

    if (range && range.start < size) {
      const end = Math.min(range.end === undefined ? size - 1 : range.end, size - 1);
      base['Content-Range'] = 'bytes ' + range.start + '-' + end + '/' + size;
      base['Content-Length'] = String(end - range.start + 1);
      res.writeHead(206, base);
      const rs = fs.createReadStream(filePath, { start: range.start, end });
      res.on('close', () => { try { rs.destroy(); } catch {} });
      rs.pipe(res);
      return;
    }

    base['Content-Length'] = String(size);
    res.writeHead(200, base);
    const rs = fs.createReadStream(filePath);
    res.on('close', () => { try { rs.destroy(); } catch {} });
    rs.pipe(res);
  }

  server.listen(port, () => {
    console.log(`[vibecatch-remote-worker] listening on http://127.0.0.1:${port}`);
  });

  return server;
}

// ---------------------------------------------------------------------------
// Main guard — server starts ONLY when executed directly
// ---------------------------------------------------------------------------

const _isDirectlyExecuted = (() => {
  if (process.env.VIBECATCH_WORKER_SERVE === '1') return true;
  const argv1 = process.argv[1];
  if (!argv1) return false;
  try {
    const scriptPathname = new URL(import.meta.url).pathname;
    const normArg = argv1.replace(/\\/g, '/');
    const normScript = scriptPathname.replace(/\\/g, '/');
    return normArg === normScript || normArg.endsWith(normScript) || normScript.endsWith(normArg);
  } catch {
    return false;
  }
})();

if (_isDirectlyExecuted) {
  const port = Number(process.env.VIBECATCH_WORKER_PORT) || Number(process.env.PORT) || 8795;
  startServer(port);
}
